<a href="https://colab.research.google.com/github/DEVA266/training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])


In [3]:
print(a)

[1 2 3]


In [4]:
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a,b)
print("These values are real")

[1 2 3] [[1 2 3]
 [4 5 6]]
These values are real


In [6]:
print("Now it is added in the VS code editor")

Now it is added in the VS code editor


In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
b[1,1]

np.int64(5)

In [9]:
print(a[1])

2


In [10]:
c = np.array([[1,2,3,4,5,6,7,8,9],[0,11,12,13,14,15,16,17,18]])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [11]:
print(c[1,:])

[ 0 11 12 13 14 15 16 17 18]


In [12]:
print(c[1,1:5])

[11 12 13 14]


In [13]:
c[:,5]

array([ 6, 15])

In [14]:
print(c[1,2:8:2])

[12 14 16]


In [15]:
print(c[0:1:1,6])

[7]


In [16]:
d = np.array([[[1,2],[3,4]],[[5,8],[11,12]],[[1,2],[3,4]]])
print(d.shape)


(3, 2, 2)


Initializing matrix

In [17]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [18]:
print(np.ones((2,3),dtype="int32"))

[[1 1 1]
 [1 1 1]]


In [19]:
print(np.full((2,5),11))

[[11 11 11 11 11]
 [11 11 11 11 11]]


In [20]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [21]:
print(np.full_like(c,7))

[[7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]


In [22]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [23]:
print(np.full(c.shape,9))

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [24]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [25]:
np.random.rand(4,2)

array([[0.75970098, 0.15841931],
       [0.6775299 , 0.63892929],
       [0.51101813, 0.98183093],
       [0.03265275, 0.39026584]])

In [26]:
print(np.random.rand(4,2))

[[0.72047911 0.57414971]
 [0.5748268  0.77207511]
 [0.53910095 0.42405578]
 [0.39060097 0.20501924]]


In [27]:
print(np.random.random_sample(c.shape))

[[0.8225596  0.81748224 0.69387809 0.11713577 0.50251718 0.38592793
  0.65097663 0.41726428 0.42450924]
 [0.31870882 0.4738893  0.74662269 0.88579646 0.23563361 0.0168959
  0.39983696 0.62143539 0.66269489]]


In [28]:
print(np.random.randint(c.shape))

[0 6]


In [29]:
print(np.random.randn(2,3))

[[-0.5799514   0.66607913  0.2103849 ]
 [ 1.02422776  0.63539867  0.42392269]]


To print Random of integers in numpy

In [30]:
# random.randint(start_value,End_value,size of the matrix)
print(np.random.randint(2,5,size=(3,4)))

[[4 2 4 4]
 [3 4 4 3]
 [4 4 3 2]]


In [31]:
print(np.random.randint(19,size=(3,7)))

[[18 11 15 14 18  9  5]
 [12 15 16 14  0  5 18]
 [ 5  8  2  7  6  3 14]]


In [32]:
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  8]
  [11 12]]

 [[ 1  2]
  [ 3  4]]]


To have a identity matrix
we use identity function

In [33]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [35]:
# Repeating an array
# if we want to repeat an array then we use repeat function
print(a)
a = np.array([[1,2,3]])
# to use the axis then the array want to be more than one dimensional
print(np.repeat(a,5,axis=0))

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
output = np.ones([5,5])
print(output)
z = np.zeros([3,3])
print(z)
z[1,1]=9
print(z)
print(output[1:4,1:4])
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
display(output)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Copying array
# if we copy the array using equal to operator then all the changes are made in the copy of the array we be effected in the original array so use the copy function present in the numpy to copy the array available
# to copy the array to another variable use the copy function
print(a)
a = np.array([1,2,3])
b = a
b[1] = 5
print(a)

# so to avoid this
# we use the copy function
b = a.copy()
print(a)
print(b)
b[1]=2
print(b)
print(a)


[[1 2 3]]
[1 5 3]
[1 5 3]
[1 5 3]
[1 2 3]
[1 5 3]


In [40]:
a = np.full((2,3),2)
print(a)
b = np.ones((3,4))
print(b)
print(np.matmul(a,b))

[[2 2 2]
 [2 2 2]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]
