<a href="https://colab.research.google.com/github/DEVA266/training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])


In [3]:
print(a)

[1 2 3]


In [4]:
print(b)

[[1 2 3]
 [4 5 6]]
