<a href="https://colab.research.google.com/github/DEVA266/training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])


In [3]:
print(a)

[1 2 3]


In [4]:
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a,b)
print("These values are real")

[1 2 3] [[1 2 3]
 [4 5 6]]
These values are real


In [6]:
print("Now it is added in the VS code editor")

Now it is added in the VS code editor


In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
b[1,1]

np.int64(5)

In [9]:
print(a[1])

2


In [10]:
c = np.array([[1,2,3,4,5,6,7,8,9],[0,11,12,13,14,15,16,17,18]])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [11]:
print(c[1,:])

[ 0 11 12 13 14 15 16 17 18]


In [12]:
print(c[1,1:5])

[11 12 13 14]


In [13]:
c[:,5]

array([ 6, 15])

In [14]:
print(c[1,2:8:2])

[12 14 16]


In [15]:
print(c[0:1:1,6])

[7]


In [16]:
d = np.array([[[1,2],[3,4]],[[5,8],[11,12]],[[1,2],[3,4]]])
print(d.shape)


(3, 2, 2)


Initializing matrix

In [17]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [18]:
print(np.ones((2,3),dtype="int32"))

[[1 1 1]
 [1 1 1]]


In [19]:
print(np.full((2,5),11))

[[11 11 11 11 11]
 [11 11 11 11 11]]


In [20]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [21]:
print(np.full_like(c,7))

[[7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]


In [22]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [23]:
print(np.full(c.shape,9))

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [24]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [25]:
np.random.rand(4,2)

array([[0.20066103, 0.90305313],
       [0.70679316, 0.14582453],
       [0.46124061, 0.50248411],
       [0.51075882, 0.94222708]])

In [26]:
print(np.random.rand(4,2))

[[0.30904185 0.02393756]
 [0.83479228 0.85049989]
 [0.85944481 0.64193382]
 [0.61790241 0.99422346]]


In [27]:
print(np.random.random_sample(c.shape))

[[0.32082752 0.8870464  0.56155345 0.34932711 0.25493679 0.8187094
  0.57415034 0.2410029  0.79370077]
 [0.69337537 0.32689854 0.86564531 0.09537806 0.53973925 0.33857304
  0.24965942 0.57944329 0.55685965]]


In [28]:
print(np.random.randint(c.shape))

[1 8]


In [29]:
print(np.random.randn(2,3))

[[ 1.03766685 -0.7265232  -0.46606157]
 [ 0.66729302  1.31418497  0.59868085]]


To print Random of integers in numpy

In [30]:
# random.randint(start_value,End_value,size of the matrix)
print(np.random.randint(2,5,size=(3,4)))

[[3 4 4 4]
 [4 4 4 3]
 [2 2 2 4]]


In [31]:
print(np.random.randint(19,size=(3,7)))

[[17  1  9  7  8 12 17]
 [ 3 10 15  7  6 18  9]
 [ 0 18  6 12  8  8  2]]


In [32]:
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  8]
  [11 12]]

 [[ 1  2]
  [ 3  4]]]
