<a href="https://colab.research.google.com/github/DEVA266/training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])


In [3]:
print(a)

[1 2 3]


In [4]:
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a,b)
print("These values are real")

[1 2 3] [[1 2 3]
 [4 5 6]]
These values are real


In [6]:
print("Now it is added in the VS code editor")

Now it is added in the VS code editor


In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
b[1,1]

np.int64(5)

In [9]:
print(a[1])

2


In [10]:
c = np.array([[1,2,3,4,5,6,7,8,9],[0,11,12,13,14,15,16,17,18]])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [11]:
print(c[1,:])

[ 0 11 12 13 14 15 16 17 18]


In [12]:
print(c[1,1:5])

[11 12 13 14]


In [13]:
c[:,5]

array([ 6, 15])

In [14]:
print(c[1,2:8:2])

[12 14 16]


In [15]:
print(c[0:1:1,6])

[7]


In [16]:
d = np.array([[[1,2],[3,4]],[[5,8],[11,12]],[[1,2],[3,4]]])
print(d.shape)


(3, 2, 2)


Initializing matrix

In [17]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [18]:
print(np.ones((2,3),dtype="int32"))

[[1 1 1]
 [1 1 1]]


In [19]:
print(np.full((2,5),11))

[[11 11 11 11 11]
 [11 11 11 11 11]]


In [20]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [21]:
print(np.full_like(c,7))

[[7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]


In [22]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [23]:
print(np.full(c.shape,9))

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [24]:
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]


In [27]:
np.random.rand(4,2)

array([[0.99553988, 0.86125527],
       [0.42986664, 0.98698523],
       [0.90762726, 0.61395065],
       [0.47450763, 0.93668356]])

In [28]:
print(np.random.rand(4,2))

[[0.88810478 0.78493882]
 [0.18404056 0.26521176]
 [0.79996288 0.91577408]
 [0.90946338 0.81348709]]


In [29]:
print(np.random.random_sample(c.shape))

[[0.73818282 0.26385479 0.60986032 0.02689986 0.30608534 0.79790252
  0.39680802 0.05563395 0.08059118]
 [0.28315547 0.48802533 0.25734631 0.47266388 0.07170273 0.03048593
  0.78728654 0.4426687  0.72785119]]


In [30]:
print(np.random.randint(c.shape))

[1 8]


In [36]:
print(np.random.randn(2,3))

[[-0.68579428 -0.00151391  1.04525017]
 [-1.03770119  0.79981038 -0.19612493]]


To print Random of integers in numpy

In [37]:
# random.randint(start_value,End_value,size of the matrix)
print(np.random.randint(2,5,size=(3,4)))

[[3 4 4 2]
 [3 4 2 3]
 [2 4 4 2]]


In [41]:
print(np.random.randint(19,size=(3,7)))

[[18 17  7  6 17 10  3]
 [ 9  2  1  8 18 15  2]
 [ 4 12 15  6  9  3 18]]


In [42]:
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  8]
  [11 12]]

 [[ 1  2]
  [ 3  4]]]
